# site settings
title: Grid Builder | Jeremias Menichelli
author: Jeremias Menichelli
description: "Tool to help you calculate fluid grids very easily and download the result."
url: "http://jeremenichelli.github.io/gridbuilder"
baseurl: /gridbuilder

# build settings
port: 5000
highlighter: pygments
markdown: redcarpet
